filter:
    excluded_paths:
        - files/*
        - cache/*
        - system/locale/*
        - system/config/*
        - system/modules/backend/templates/*
        - system/modules/frontend/templates/*
        - system/modules/mobile/templates/*
