preset: psr2

finder:
  not-path:
    - "files"
    - "cache"
    - "system/libraries"
    - "system/locale"
    - "system/config"
    - "system/help"
<<<<<<< HEAD
    - "*/templates"
=======
    - "*template*"
>>>>>>> d140b5f9bd0ee506de34910c2cbaff7c97336113
