preset: psr2

enabled:
  - long_array_syntax
  - return

finder:
  exclude:
    - files
    - cache
    - system/libraries
    - system/locale
    - system/config
    - system/help
  name:
    - "*.php"
