preset: psr2

enabled:
  - ordered_class_elements

finder:
  not-path:
    - "files"
    - "cache"
    - "system/libraries"
    - "system/locale"
    - "system/config"
    - "system/help"
    - "system/modules/backend/templates"
    - "system/modules/frontend/templates"
    - "system/modules/mobile/templates"
